### ISSUE TITLE
Amount in words differs from amount in numbers by $0.01

### ISSUE THREAD

**Issue by jmacxx** [DickyT/check-de-go#9]
![image](https://user-images.githubusercontent.com/47253594/94614110-44905d00-026b-11eb-8392-d8cdd02515ef.png)

I came across an issue where the amount entered was 14.70 but the amount in the center part of the check read as "FOURTEEN AND 69/100".  The same thing happened when entering other fractional dollar amounts.  Tracked it down to `Check.tsx#L34` which results in a floating point number that looks like 0.6899999999999".

      const amountDecimalNumbers = amount - amountInt;

Changing it to this fixes the issue:

      const amountDecimalNumbers = (amount - amountInt).toFixed(2);

----

By the way, thankyou for creating this amazing piece of software.  Its useful not only for creating checks but also a good example electron project.  It is inspiring and useful, I love it!

**Comment by DickyT** [comment]
Thank you so much for this bug fix, I would submit a new version soon to resolve this issue
